filegroup(
    name = "gradle",
    srcs = ["gradle-2.14.1-bin.zip"],
    visibility = ["//visibility:public"],
)

# gradle-api jar, as generated by gradle when using the gradleApi() magic dependency.
java_import(
    name = "gradle-api.jar",
    jars = ["gradle-api-2.14.1.jar"],
    visibility = ["//visibility:public"],
)
