#######
# Gradle 2.14.1
#######

# do not use directly. Use //tools/base/build-system:gradle
filegroup(
    name = "gradle-distrib-2.14.1",
    srcs = ["gradle-2.14.1-bin.zip"],
    visibility = ["//tools/base/build-system:__pkg__"],
)

# gradle-api jar, as generated by gradle when using the gradleApi() magic dependency.
# do not use directly. Use
# //tools/base/build-system:gradle-api_neverlink
# //tools/base/build-system:gradle-api
filegroup(
    name = "gradle-api-2.14.1",
    srcs = ["gradle-api-2.14.1.jar"],
    visibility = ["//tools/base/build-system:__pkg__"],
)

#######
# gradle 3.2
#######

# do not use directly. Use //tools/base/build-system:gradle
filegroup(
    name = "gradle-distrib-3.2",
    srcs = ["gradle-3.2-bin.zip"],
    visibility = ["//tools/base/build-system:__pkg__"],
)

# gradle-api jar, as generated by gradle when using the gradleApi() magic dependency.
# do not use directly. Use
# //tools/base/build-system:gradle-api_neverlink
# //tools/base/build-system:gradle-api
filegroup(
    name = "gradle-api-3.2",
    srcs = ["gradle-api-3.2.jar"],
    visibility = ["//tools/base/build-system:__pkg__"],
)

